export { default as Fullpage } from './Fullpage.svelte'
export { default as FullpageSection } from './FullpageSection.svelte'
export { default as FullpageSlide } from './FullpageSlide.svelte'
export { useFullpage, useFullpageSection } from './context'
export { prefersReducedMotion } from './scroll'
export type * from './types'
